/**
 * A phrase generated on any client must restore the same identity on every
 * other client.
 *
 * This is the test that would have caught the fragmentation: three clients
 * each carried a different wordlist, so a phrase generated on web was
 * rejected outright by mobile's restore screen. Wordlists are only half of
 * it — the derivation has to agree too, so this checks the Ghost Address
 * actually produced, not just that the words were accepted.
 *
 * The three derivations under test:
 *   - mobile  — src/utils/crypto.js deriveGhostIdentity (PBKDF2-HMAC-SHA512)
 *   - gmp-core — src/identity.ts deriveIdentityFromSeedPhrase, the node that
 *     actually joins the mesh, and the address the web app displays (the web
 *     client does not derive it locally; it reads it off the bridge)
 *
 * Run with: node test/phrase-roundtrip.test.mjs
 */
import assert from 'assert';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const shared = await import(path.join(root, 'shared/wordlist.js'));
const phraseEntry = await import(path.join(root, 'mobile/src/utils/phrase-entry.js'));

// ── mobile's crypto, with the keystore stubbed (it cannot load outside the app)
const mobileSrc = path.join(root, 'mobile/src/utils/crypto.js');
const stubbed = fs.readFileSync(mobileSrc, 'utf8')
  // Node cannot parse react-native's Flow source; the native PBKDF2 module is
  // absent here anyway, so this exercises the @noble fallback.
  .replace("import {NativeModules} from 'react-native';", 'const NativeModules = {};')
  .replace(/import \* as Keychain from 'react-native-keychain';/,
    'const Keychain = {setGenericPassword: async () => true, getGenericPassword: async () => false, ' +
    'resetGenericPassword: async () => true, getSupportedBiometryType: async () => null, ' +
    'ACCESS_CONTROL: {BIOMETRY_ANY_OR_DEVICE_PASSCODE: 0}, ACCESSIBLE: {WHEN_UNLOCKED_THIS_DEVICE_ONLY: 0}};')
  .replace(/from '\.\/wordlist'/, `from '${path.join(root, 'mobile/src/utils/wordlist.js')}'`)
  .replace(/from '\.\/ghost-address'/, `from '${path.join(root, 'mobile/src/utils/ghost-address.js')}'`);
const tmp = path.join(root, 'mobile', `.roundtrip-${process.pid}.mjs`);
fs.writeFileSync(tmp, stubbed);
let MobileCrypto;
try { MobileCrypto = (await import(`file://${tmp}`)).default; }
finally { fs.rmSync(tmp, {force: true}); }

// ── gmp-core's derivation (the node that actually joins the mesh)
const {deriveIdentityFromSeedPhrase} = await import(path.join(root, 'gmp-core/dist/identity.js'));
const {ghostAddressFromNodeId} = await import(path.join(root, 'gmp-core/dist/ghost-address.js'));
const toHex = (b) => Buffer.from(b).toString('hex');

async function ghostAddressViaMobile(words) {
  return (await MobileCrypto.deriveGhostIdentity(words)).ghostAddress;
}
async function ghostAddressViaNode(words) {
  const id = await deriveIdentityFromSeedPhrase(words.join(' '));
  return ghostAddressFromNodeId(id.nodeIdHex || toHex(id.nodeId));
}

// ── the web app's generator, lifted out of index.html so the real one is tested
function loadWebGenerator() {
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const m = /const generateSeedPhrase = async \(\) => \{([\s\S]*?)\n  \};/.exec(html);
  assert.ok(m, 'index.html no longer declares generateSeedPhrase in the expected form');
  // The real body loads the wordlist through a module import and a cached
  // BIP39_WORDS binding; supply both and run it verbatim otherwise.
  const body = m[1]
    .replace(/if \(!BIP39_WORDS\) \{[\s\S]*?\n    \}/, '')
    .replace(/if \(!BIP39_WORDS\) \{[\s\S]*?\n    \}/, '');
  return new Function('BIP39_WORDS', 'crypto', `return (async () => {${body}})();`);
}

let failures = 0;
const tests = [];
const test = (name, fn) => tests.push([name, fn]);

test('a phrase generated by the web app restores on mobile and on the node', async () => {
  const gen = loadWebGenerator();
  for (let i = 0; i < 5; i++) {
    const words = await gen(shared.BIP39_WORDS, globalThis.crypto);
    assert.strictEqual(words.length, 12, 'web must generate 12 words');

    // It must be accepted by mobile's restore screen.
    const check = phraseEntry.validatePhrase(words);
    assert.strictEqual(check.ok, true,
      `mobile rejected a web-generated phrase: ${words.join(' ')} (unknown at ${check.unknown})`);
    assert.deepStrictEqual(check.legacy, [], 'a new phrase must contain no legacy-only words');

    // And it must derive the same identity everywhere.
    const [onMobile, onNode] = await Promise.all([
      ghostAddressViaMobile(words), ghostAddressViaNode(words),
    ]);
    assert.strictEqual(onMobile, onNode,
      `Ghost Address differs for "${words.join(' ')}": mobile ${onMobile} vs node ${onNode}`);
    assert.ok(/^GHOST-/.test(onMobile), `unexpected address form: ${onMobile}`);
  }
});

test('a phrase generated on mobile restores on the node', async () => {
  for (let i = 0; i < 5; i++) {
    const words = MobileCrypto.generateSeedPhrase();
    assert.strictEqual(words.length, 12);
    for (const w of words) {
      assert.ok(shared.BIP39_WORDS.includes(w),
        `mobile generated "${w}", which is not a BIP-39 word`);
    }
    const [onMobile, onNode] = await Promise.all([
      ghostAddressViaMobile(words), ghostAddressViaNode(words),
    ]);
    assert.strictEqual(onMobile, onNode,
      `Ghost Address differs for "${words.join(' ')}"`);
  }
});

test('a phrase from an OLD mobile build still restores everywhere', async () => {
  // Built the way the pre-2.1 app built them: from the 575-word list,
  // including words that are not BIP-39 at all.
  const legacyPhrase = [
    'mitten', 'circuit', 'rainbow', 'signal', 'texture', 'global',
    'abandon', 'ability', 'able', 'about', 'above', 'absent',
  ];
  const check = phraseEntry.validatePhrase(legacyPhrase);
  assert.strictEqual(check.ok, true, 'an old phrase must still be accepted');
  assert.ok(check.legacy.length === 6, 'the six non-BIP-39 words must be flagged as legacy');

  const [onMobile, onNode] = await Promise.all([
    ghostAddressViaMobile(legacyPhrase), ghostAddressViaNode(legacyPhrase),
  ]);
  assert.strictEqual(onMobile, onNode, 'an old phrase must derive one identity everywhere');
});

test('the derivation is stable, not just internally consistent', async () => {
  // A fixed phrase pinned to a known address. If a KDF parameter is ever
  // changed on one platform, this fails rather than silently orphaning
  // everybody's identity.
  const words = 'abuse morning urban captain vendor olympic forest unlock flavor ocean vibrant elite'.split(' ');
  const expected = 'GHOST-Z3H-NMX-81T';
  assert.strictEqual(await ghostAddressViaMobile(words), expected, 'mobile derivation changed');
  assert.strictEqual(await ghostAddressViaNode(words), expected, 'node derivation changed');
});

test('a one-word typo yields a different identity (why the address is confirmed)', async () => {
  const a = 'abuse morning urban captain vendor olympic forest unlock flavor ocean vibrant elite'.split(' ');
  const b = [...a.slice(0, 11), 'zebra'];
  assert.notStrictEqual(await ghostAddressViaMobile(a), await ghostAddressViaMobile(b));
});

for (const [name, fn] of tests) {
  try { await fn(); console.log(`  ok  ${name}`); }
  catch (err) { failures++; console.error(`  FAIL  ${name}\n        ${err.message}`); }
}
if (failures) { console.error(`\n${failures} phrase-roundtrip test(s) failed`); process.exit(1); }
console.log('\nAll phrase-roundtrip tests passed');
