// build-vendor.js — produces vendor/ from the pinned node_modules copies.
//
// The page used to pull React, ReactDOM, htm and tweetnacl straight from
// esm.sh and unpkg at runtime, with no integrity checking: whatever those
// hosts served executed with full access to the user's keys and message
// history. These are the same versions, resolved once, reviewed, and served
// from the app's own origin.
//
// The web fonts are here for the same reason, with an extra one: a request to
// fonts.googleapis.com happens before the user has typed anything, and carries
// their IP and the timing of every session to a third party. That is precisely
// the metadata the rest of this app is built to avoid producing.
//
// Run: npm run build:vendor          (skips fonts; they rarely change)
//      npm run build:vendor -- --fonts   (re-fetches the fonts too)
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const ROOT = __dirname;
const VENDOR_DIR = path.join(ROOT, 'vendor');
const VENDOR_SRC = path.join(ROOT, 'vendor-src');
const FONTS_DIR = path.join(VENDOR_DIR, 'fonts');

// Exactly the families and weights index.html asks for. Google returns variable
// fonts, so this is 16 files rather than one per weight.
const FONTS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Outfit:wght@300;400;500;600;700;800' +
  '&family=JetBrains+Mono:wght@300;400;500;600;700;800' +
  '&family=Space+Grotesk:wght@300;400;500;600;700' +
  '&family=Nunito:wght@300;400;500;600;700;800;900' +
  '&display=swap';

// Google serves woff2 only to browsers it recognises; without this it returns
// the ancient truetype CSS instead.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

if (!fs.existsSync(VENDOR_DIR)) fs.mkdirSync(VENDOR_DIR);

async function buildFonts() {
  if (!fs.existsSync(FONTS_DIR)) fs.mkdirSync(FONTS_DIR, { recursive: true });

  const css = await (await fetch(FONTS_URL, { headers: { 'User-Agent': UA } })).text();
  if (!css.includes('@font-face')) throw new Error('unexpected response from Google Fonts');

  // Each @font-face is preceded by a /* subset */ comment; the pair of family
  // and subset is what names the local file.
  const faces = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{[^}]*?font-family:\s*'([^']+)'[^}]*?url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/g)];
  const seen = new Map();
  for (const [, subset, family, url] of faces) {
    if (seen.has(url)) continue;
    const name = `${family.toLowerCase().replace(/ /g, '-')}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    if (buf.length < 500) throw new Error(`suspiciously small font: ${name}`);
    fs.writeFileSync(path.join(FONTS_DIR, name), buf);
    seen.set(url, './' + name);
  }

  let local = css;
  for (const [url, rel] of seen) local = local.split(url).join(rel);
  if (local.includes('fonts.gstatic.com')) throw new Error('a font URL was left pointing at Google');

  fs.writeFileSync(path.join(FONTS_DIR, 'fonts.css'),
    '/* Vendored Google Fonts \u2014 generated by build-vendor.js, do not hand-edit.\n' +
    ' * Regenerate with: npm run build:vendor -- --fonts\n */\n' + local);
  console.log(`fonts: ${seen.size} woff2 files + fonts.css`);
}

async function main() {
  // runtime.js carries the actual library code; the three specifier shims are
  // built with it marked external so they share one instance at runtime, and
  // the browser resolves './runtime.js' relative to vendor/.
  await esbuild.build({
    entryPoints: [path.join(VENDOR_SRC, 'runtime.js')],
    bundle: true,
    format: 'esm',
    target: 'es2020',
    minify: true,
    platform: 'browser',
    define: { 'process.env.NODE_ENV': '"production"' },
    outfile: path.join(VENDOR_DIR, 'runtime.js')
  });

  for (const name of ['react.js', 'react-dom-client.js', 'htm.js']) {
    await esbuild.build({
      entryPoints: [path.join(VENDOR_SRC, name)],
      bundle: true,
      format: 'esm',
      target: 'es2020',
      minify: true,
      platform: 'browser',
      external: ['./runtime.js'],
      outfile: path.join(VENDOR_DIR, name)
    });
  }

  // tweetnacl ships a prebuilt browser file; copy it as-is.
  const nacl = path.join(ROOT, 'node_modules', 'tweetnacl', 'nacl-fast.min.js');
  fs.copyFileSync(nacl, path.join(VENDOR_DIR, 'nacl-fast.min.js'));

  // Fonts are only re-fetched on request: they change far less often than the
  // JS, and the rest of this script must keep working with no network.
  if (process.argv.includes('--fonts')) await buildFonts();

  for (const f of fs.readdirSync(VENDOR_DIR)) {
    const p = path.join(VENDOR_DIR, f);
    const st = fs.statSync(p);
    if (st.isDirectory()) {
      const n = fs.readdirSync(p).length;
      console.log(`${(f + '/').padEnd(22)} ${String(n).padStart(8)} files`);
      continue;
    }
    console.log(`${f.padEnd(22)} ${String(st.size).padStart(8)} bytes`);
  }
}

main().catch((e) => {console.error(e);process.exit(1);});
