export function loadConfig(customOptions?: {}): {
    GMP_PORT: number;
    GMP_BRIDGE_PORT: number;
    GMP_BRIDGE_HOST: string;
    GMP_MIN_PEERS: number;
    GMP_MAX_PEERS: number;
    GMP_MAX_CONNECTIONS: number;
    GMP_HELLO_TIMEOUT_MS: number;
    GMP_HANDSHAKE_TIMEOUT_MS: number;
    GMP_PING_INTERVAL_MS: number;
    GMP_PING_TIMEOUT_MS: number;
    GMP_TIMESTAMP_WINDOW_MS: number;
    GMP_BOOTSTRAP_STAGE1_TIMEOUT_MS: number;
    GMP_BOOTSTRAP_STAGE2_TIMEOUT_MS: number;
    GMP_REBOOTSTRAP_BACKOFF_INITIAL_MS: number;
    GMP_RATE_LIMIT_WINDOW_MS: number;
    GMP_RATE_LIMIT_MAX_PER_IP: number;
    GMP_RATE_LIMIT_MAX_GLOBAL: number;
    GMP_FORWARD_RATE_LIMIT_PER_SOURCE: number;
    GMP_PEER_REQUEST_RATE_LIMIT_INTERVAL_MS: number;
    GMP_SESSION_KEY_LRU_SIZE: number;
    GMP_SEQUENCE_NUM_LRU_SIZE: number;
    GMP_NONCE_PRUNE_AGE_MS: number;
    GMP_ROUTE_EXPIRY_MS: number;
    GMP_TOPOLOGY_TTL: number;
    GMP_MESSAGE_HOP_LIMIT: number;
    GMP_REANNOUNCE_INTERVAL_MS: number;
    GMP_PEER_CACHE_MAX_SIZE: number;
    GMP_PEER_CACHE_PRUNE_FAILURE_THRESHOLD: number;
    GMP_PEER_CACHE_PRUNE_AGE_DAYS: number;
    GMP_METRICS_PORT: number;
    GMP_LAN_DISCOVERY: boolean;
    GMP_LAN_DISCOVERY_PORT: number;
    GMP_LAN_DISCOVERY_GROUP: string;
    GMP_PUBLIC_PEERS_PATH: string;
    GMP_LOG_LEVEL: string;
    GMP_LOG_TO_FILE: boolean;
    GMP_LOG_TO_CONSOLE: boolean;
    GMP_BAN_DURATION_MS: number;
    GMP_REPUTATION_RECOVERY_INTERVAL_MS: number;
};
export namespace DEFAULTS {
    let GMP_PORT: number;
    let GMP_BRIDGE_PORT: number;
    let GMP_BRIDGE_HOST: string;
    let GMP_MIN_PEERS: number;
    let GMP_MAX_PEERS: number;
    let GMP_MAX_CONNECTIONS: number;
    let GMP_HELLO_TIMEOUT_MS: number;
    let GMP_HANDSHAKE_TIMEOUT_MS: number;
    let GMP_PING_INTERVAL_MS: number;
    let GMP_PING_TIMEOUT_MS: number;
    let GMP_TIMESTAMP_WINDOW_MS: number;
    let GMP_BOOTSTRAP_STAGE1_TIMEOUT_MS: number;
    let GMP_BOOTSTRAP_STAGE2_TIMEOUT_MS: number;
    let GMP_REBOOTSTRAP_BACKOFF_INITIAL_MS: number;
    let GMP_RATE_LIMIT_WINDOW_MS: number;
    let GMP_RATE_LIMIT_MAX_PER_IP: number;
    let GMP_RATE_LIMIT_MAX_GLOBAL: number;
    let GMP_FORWARD_RATE_LIMIT_PER_SOURCE: number;
    let GMP_PEER_REQUEST_RATE_LIMIT_INTERVAL_MS: number;
    let GMP_SESSION_KEY_LRU_SIZE: number;
    let GMP_SEQUENCE_NUM_LRU_SIZE: number;
    let GMP_NONCE_PRUNE_AGE_MS: number;
    let GMP_ROUTE_EXPIRY_MS: number;
    let GMP_TOPOLOGY_TTL: number;
    let GMP_MESSAGE_HOP_LIMIT: number;
    let GMP_REANNOUNCE_INTERVAL_MS: number;
    let GMP_PEER_CACHE_MAX_SIZE: number;
    let GMP_PEER_CACHE_PRUNE_FAILURE_THRESHOLD: number;
    let GMP_PEER_CACHE_PRUNE_AGE_DAYS: number;
    let GMP_METRICS_PORT: number;
    let GMP_LAN_DISCOVERY: boolean;
    let GMP_LAN_DISCOVERY_PORT: number;
    let GMP_LAN_DISCOVERY_GROUP: string;
    let GMP_PUBLIC_PEERS_PATH: string;
    let GMP_LOG_LEVEL: string;
    let GMP_LOG_TO_FILE: boolean;
    let GMP_LOG_TO_CONSOLE: boolean;
    let GMP_BAN_DURATION_MS: number;
    let GMP_REPUTATION_RECOVERY_INTERVAL_MS: number;
}
export default config;
declare namespace config { }
